version: "1.0"

ingress:
  - port: 80
    expose: "public"
    mode: "http"
    target:
      - host: "api"
        port: 3000
  - port: 80
    expose: "public"
    mode: "http"
    target:
      - host: "blog"
        port: 3000
  - port: 443
    expose: "public"
    mode: "https"
    https:
      sni: "api.balena.io"
    target:
      - host: "10.10.10.1"
        port: 3000
      - host: "10.10.10.2git "
        port: 3000
